# -*- coding: utf-8 -*-
"""Funções matemáticas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VClvrK0QEajjlquoWEQjmZ_8-oyl9ftv

O programa abaixo dois números da entrada padrão e depois faz uma operação com eles. A operação pode ser uma das seguintes:

*  somaRaizes: soma a raiz quadrada do primeiro número com a raiz quadrada do
segundo (resultado é float)
*   potencia: eleva o primeiro ao segundo (resultado é inteiro)

*   multiplicaPotencias: multiplica X por Y, em que X é o primeiro número elevado ao segundo, e Y o segundo elevado ao primeiro (resultado é inteiro)
"""

import math
def somaRaizes(a,b):
 return math.sqrt(a) + math.sqrt(b)
def potencia(a,b):
 return a**b
def multiplicaPotencias(a,b):
 return (a**b) * (b**a)

a = int(input())
b = int(input())
operação = input()

if operação == "somaRaizes":
 resultado = somaRaizes(a,b)
if operação == "potencia":
 resultado = potencia(a,b)
if operação == "multiplicaPotencias":
 resultado = multiplicaPotencias(a,b)

print(f"{resultado:.2f}")